# Generated by Django 4.0.6 on 2023-01-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippinglPrice',
            new_name='shippingPrice',
        ),
    ]
